print("In The Name Of God")
print("In The Name Of \"God\"")
print("In The Name Of \n God")
print("In The Name Of \t God")
print("In The\\Name Of God")
print("In The Name Of \bGod")
print("please come \rhere")
print("In The Name\a Of God")
print("In The Name\f Of God")
print("In The \vName Of God")